// Use real implementations for these integration tests
jest.unmock('@/contexts/CartContext')
jest.unmock('@/hooks/useCart')

import React from 'react'
import { render, screen, act } from '@testing-library/react'
import { CartProvider } from '../CartContext'
import { useCart } from '@/hooks/useCart'

// Component to test the hook
function TestComponent() {
  const { cart, addToCart, removeFromCart, clearCart, totalItems, acceptAuthoritativePriceQuote } = useCart()

  const handleRemove = () => {
    // removeFromCart uses uniqueId, which is generated by addToCart
    if (cart.length > 0) {
      removeFromCart(cart[0].uniqueId)
    }
  }

  return (
    <div>
      <div data-testid="cart-count">{totalItems}</div>
      <div data-testid="cart-items">{JSON.stringify(cart)}</div>
      <button onClick={() => addToCart({
        id: '1',
        title: 'Test Tour',
        price: 100,
        quantity: 1,
        childQuantity: 0,
        infantQuantity: 0,
        selectedDate: '2024-01-01',
        selectedTime: '10:00',
        selectedBookingOption: { id: 'standard-default', pricingKey: 'standard', title: 'Standard', price: 100 },
        guestPrices: { adult: 100, child: 50, infant: 0 },
        priceVersion: 1,
      } as any, false)}>
        Add Item
      </button>
      <button onClick={() => void acceptAuthoritativePriceQuote({
        tourId: '1',
        tourTitle: 'Test Tour',
        optionKey: 'standard',
        date: '2024-01-01',
        time: '10:00',
        currency: 'USD',
        prices: { adult: 120, child: 65, infant: 5 },
        version: 2,
        executionId: 'execution-2',
        overrideId: 'override-2',
        source: 'override',
      })}>
        Accept Quote
      </button>
      <button onClick={handleRemove}>Remove Item</button>
      <button onClick={clearCart}>Clear Cart</button>
    </div>
  )
}

// Mock localStorage
const localStorageMock = (() => {
  let store: Record<string, string> = {}
  return {
    getItem: (key: string) => store[key] || null,
    setItem: (key: string, value: string) => {
      store[key] = value.toString()
    },
    removeItem: (key: string) => {
      delete store[key]
    },
    clear: () => {
      store = {}
    },
  }
})()

Object.defineProperty(window, 'localStorage', {
  value: localStorageMock,
})

describe('CartContext', () => {
  beforeEach(() => {
    localStorageMock.clear()
  })

  it('should initialize with empty cart', () => {
    render(
      <CartProvider>
        <TestComponent />
      </CartProvider>
    )

    expect(screen.getByTestId('cart-count')).toHaveTextContent('0')
  })

  it('should add item to cart', async () => {
    render(
      <CartProvider>
        <TestComponent />
      </CartProvider>
    )

    const addButton = screen.getByText('Add Item')

    await act(async () => {
      addButton.click()
    })

    expect(screen.getByTestId('cart-count')).toHaveTextContent('1')
  })

  it('should remove item from cart', async () => {
    render(
      <CartProvider>
        <TestComponent />
      </CartProvider>
    )

    const addButton = screen.getByText('Add Item')
    const removeButton = screen.getByText('Remove Item')

    await act(async () => {
      addButton.click()
    })

    expect(screen.getByTestId('cart-count')).toHaveTextContent('1')

    await act(async () => {
      removeButton.click()
    })

    expect(screen.getByTestId('cart-count')).toHaveTextContent('0')
  })

  it('should clear cart', async () => {
    render(
      <CartProvider>
        <TestComponent />
      </CartProvider>
    )

    const addButton = screen.getByText('Add Item')
    const clearButton = screen.getByText('Clear Cart')

    await act(async () => {
      addButton.click()
      addButton.click()
    })

    expect(screen.getByTestId('cart-count')).toHaveTextContent('2')

    await act(async () => {
      clearButton.click()
    })

    expect(screen.getByTestId('cart-count')).toHaveTextContent('0')
  })

  it('should persist cart to localStorage', async () => {
    render(
      <CartProvider>
        <TestComponent />
      </CartProvider>
    )

    const addButton = screen.getByText('Add Item')

    await act(async () => {
      addButton.click()
    })

    // Wait for useEffect to run
    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 100))
    })

    const stored = localStorage.getItem('cart')
    expect(stored).toBeTruthy()
  })

  it('atomically accepts and persists the complete authoritative quote', async () => {
    render(
      <CartProvider>
        <TestComponent />
      </CartProvider>
    )

    await act(async () => {
      screen.getByText('Add Item').click()
    })
    await act(async () => {
      screen.getByText('Accept Quote').click()
      await Promise.resolve()
    })

    const cart = JSON.parse(screen.getByTestId('cart-items').textContent || '[]')
    expect(cart[0]).toMatchObject({
      guestPrices: { adult: 120, child: 65, infant: 5 },
      priceVersion: 2,
      priceExecutionId: 'execution-2',
      priceOverrideId: 'override-2',
      priceSource: 'override',
      selectedBookingOption: { pricingKey: 'standard', price: 120 },
    })
    expect(JSON.parse(localStorage.getItem('cart') || '[]')[0]).toMatchObject({
      guestPrices: { adult: 120, child: 65, infant: 5 },
      priceVersion: 2,
      priceSource: 'override',
    })
  })
})
